# Generated by Django 2.2.1 on 2019-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=250)),
                ('file_type', models.CharField(max_length=10)),
                ('upload_file', models.CharField(max_length=1000)),
            ],
        ),
    ]
